version: "3"

services:
  db:
    # container_name: 'db'
    image: postgres:10.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    env_file: .env
    # container_name: 'web'
    build: .
    command: /src/entrypoint.sh
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
